### ISSUE TITLE
Error while joining Lemmy communities.

### ISSUE THREAD

**Issue by B1naryB0t** [induna-crewneck/Reddit-Lemmy-Migrator#8]
Program runs as normal all the way through pulling subreddits, but then this just says error while joining lemmy communities

**Comment by induna-crewneck** [comment]
If you downloaded this more than a day or so ago, please re-download. There was an error about this that was fixed.

If the issue persists, please enable debug by running "reddit-lemmy-migrator.py debug"

**Comment by B1naryB0t** [comment]
I redownloaded and now it doesn't get to the point. This is the log in command prompt after running debug:

Traceback (most recent call last):
  File "C:\Users\sprin\reddit-lemmy-migrator.py", line 69, in <module>
    driver = webdriver.Chrome(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sprin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.19045 x86_64)

**Comment by induna-crewneck** [comment]
The latest update implements an autoinstaller for the chromedriver. You can install `pip install chromedriver-autoinstaller` and run V1.4 of the script to see if this fixes your issue.

**Comment by induna-crewneck** [comment]
Closing due to no response
